title: MRI Tools
description: A community-driven directory of open-source MRI software, organized by workflow stage.
baseurl: ""
url: "https://openmritools.github.io"

exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
