# Training & Events

- name: Neurohackademy
  description: Summer institute in neuroimaging and data science at the University of Washington.
  url: https://neurohackademy.org
  date_added: 2026-06-16

- name: OHBM Brainhack
  description: Annual hackathon for collaborative neuroimaging projects, co-located with the OHBM annual meeting.
  url: https://humanbrainmapping.org/26Brainhack/
  date_added: 2026-06-16
