"""
Reads _data/tools/*.yml, queries the GitHub API for each tool with a
`github: owner/repo` field, and writes health metadata to _data/health.yml.

Status classification (based on last push date):
  active   — committed within the last 6 months
  quiet    — committed 6–24 months ago
  inactive — no commit in 2+ years, or repository is archived on GitHub

The key in health.yml is the github slug with '/' replaced by '-',
matching the lookup used in index.html:
  {{ tool.github | replace: '/', '-' }}
"""

import os
import sys
import glob
import yaml
import requests
from datetime import datetime, timezone, timedelta
from pathlib import Path

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
if not GITHUB_TOKEN:
    print("Warning: GITHUB_TOKEN not set — unauthenticated requests are rate-limited to 60/hour",
          file=sys.stderr)

HEADERS = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}
if GITHUB_TOKEN:
    HEADERS["Authorization"] = f"Bearer {GITHUB_TOKEN}"

API_BASE = "https://api.github.com/repos/{}"
NOW = datetime.now(timezone.utc)

SIX_MONTHS   = timedelta(days=183)
TWO_YEARS    = timedelta(days=730)


def classify(pushed_at: datetime, archived: bool) -> str:
    if archived:
        return "inactive"
    age = NOW - pushed_at
    if age <= SIX_MONTHS:
        return "active"
    if age <= TWO_YEARS:
        return "quiet"
    return "inactive"


def fetch_repo(slug: str) -> dict | None:
    try:
        r = requests.get(API_BASE.format(slug), headers=HEADERS, timeout=15)
        if r.status_code == 404:
            print(f"    not found (404)")
            return None
        r.raise_for_status()
    except requests.RequestException as e:
        print(f"    request failed — {e}")
        return None

    data = r.json()
    pushed_at = datetime.fromisoformat(data["pushed_at"].replace("Z", "+00:00"))
    return {
        "stars":       data["stargazers_count"],
        "last_commit": pushed_at.strftime("%Y-%m-%d"),
        "status":      classify(pushed_at, data["archived"]),
        "checked_at":  NOW.strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


def load_slugs() -> list[tuple[str, str]]:
    """Return [(display_name, owner/repo), ...] for all tools with a github field."""
    results = []
    for path in sorted(Path("_data/tools").glob("*.yml")):
        with open(path) as f:
            tools = yaml.safe_load(f) or []
        if not isinstance(tools, list):
            continue
        for tool in tools:
            slug = tool.get("github")
            if slug:
                results.append((tool.get("name", slug), slug))
    return results


def main():
    tools = load_slugs()
    print(f"Checking {len(tools)} tools with GitHub repos...")

    health = {}
    for name, slug in tools:
        key = slug.replace("/", "-")
        print(f"  {name} ({slug})...", end=" ", flush=True)
        result = fetch_repo(slug)
        if result:
            health[key] = result
            print(f"{result['status']}  [{result['last_commit']}  ★{result['stars']}]")
        else:
            print("skipped")

    out = Path("_data/health.yml")
    with open(out, "w") as f:
        f.write("# Auto-generated by scripts/update_health.py — do not edit by hand.\n")
        f.write(f"# Last run: {NOW.strftime('%Y-%m-%dT%H:%M:%SZ')}\n")
        yaml.dump(health, f, default_flow_style=False, allow_unicode=True, sort_keys=True)

    print(f"\nWrote {len(health)} entries to {out}")


if __name__ == "__main__":
    main()
